-- Build a state/UT healthcare access and readiness mart from parsed NHM MIS rows.
SELECT
    state,
    focus_group,
    population_lakh_reported,
    population_lakh,
    districts,
    cities_covered,
    cities_health_facility_mapped,
    cities_slum_mapped,
    cities_vulnerability_mapped,
    cbr,
    cdr,
    imr,
    mmr,
    tfr,
    sex_ratio,
    life_expectancy,
    nmr,
    u5mr,
    sub_centres,
    facilities_24x7 AS rural_subdistrict_facilities_24x7,
    uphcs_24x7,
    phcs,
    phcs_three_nurses,
    uphcs_operational,
    uphcs_minimum_package,
    chcs,
    uchcs_24x7,
    district_hospitals,
    facilities_24x7 + uphcs_24x7 + uchcs_24x7 AS facilities_24x7,
    sub_centres + phcs + chcs + district_hospitals AS core_public_facilities,
    100.0 * cities_health_facility_mapped / NULLIF(cities_covered, 0) AS urban_facility_mapping_pct,
    100.0 * cities_slum_mapped / NULLIF(cities_covered, 0) AS urban_slum_mapping_pct,
    100.0 * cities_vulnerability_mapped / NULLIF(cities_covered, 0) AS urban_vulnerability_mapping_pct,
    100.0 * phcs_three_nurses / NULLIF(phcs, 0) AS phc_three_nurse_readiness_pct,
    100.0 * uphcs_minimum_package / NULLIF(uphcs_operational, 0) AS uphc_minimum_package_pct,
    100000.0 * (facilities_24x7 + uphcs_24x7 + uchcs_24x7) / NULLIF(population_lakh * 100000.0, 0) AS facilities_24x7_per_100k,
    100000.0 * phcs / NULLIF(population_lakh * 100000.0, 0) AS phcs_per_100k,
    1000000.0 * district_hospitals / NULLIF(population_lakh * 100000.0, 0) AS district_hospitals_per_million,
    100000.0 * core_public_facilities / NULLIF(population_lakh * 100000.0, 0) AS core_facilities_per_100k
FROM state_raw
ORDER BY state;
